# Site settings
title: Felip Barbosa de Medeiros
description_site: 'Programador membro da <a href="https://fsf.org">FSF</a> desde 2018 que j치 administrou v치rias empresas.
Co-fundador da <a href="https://veganalimentos.com.br">Vegan</a>, ex <a href="https://www.hortminasdf.com.br/">HortMinas</a> e <a href="http://www.cebgas.com.br/">CEBGAS</a>.'
description_seo: 'Programador membro da FSF desde 2018 que j치 administrou v치rias empresas.'
url: 'https://felip.com.br/'
baseurl: ''
link: 'https://felip.com.br'
locale: pt_BR

author:
  name: 'Felip Barbosa de Medeiros'
  email: felip@vegan.ind.br
  twitter_username: fxlip
  instagram_username: bvrbosv
  github_username:  fel1p
  telegram_username: fel1p
  steam_username: mked0n
  psn_username: mked0n
  strava_link: 39646001
  discord_link: q5gWd6P
  whatsapp_number: 5561996220406

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 3
excerpt_separator: <!--mais-->
permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate', 'jekyll-localization']
exclude: ['README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
